version: "3.9"

services:
  api:
    build: .
    image: mi-app
    container_name: fastapi_app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONPATH=/app

  dashboard:
    image: mi-app
    pull_policy: never
    container_name: streamlit_app
    command: >
      streamlit run dashboard.py
      --server.port 8501
      --server.address 0.0.0.0
      --server.runOnSave true
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    depends_on:
      - api